# Generated by Django 2.0.3 on 2018-03-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('calperounce', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Recipechanges',
            fields=[
                ('chid', models.IntegerField(primary_key=True, serialize=False)),
                ('numvotes', models.IntegerField(blank=True, null=True)),
                ('amounts', models.CharField(max_length=30)),
                ('ingredients', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'recipechanges',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('appliances', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('youtubevid', models.CharField(blank=True, max_length=11, null=True)),
                ('timesrated', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('cooktime', models.IntegerField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Recipecontains',
            fields=[
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Ingredient')),
            ],
            options={
                'db_table': 'recipecontains',
            },
        ),
        migrations.CreateModel(
            name='Userrecipe',
            fields=[
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Recipes')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Users')),
            ],
            options={
                'db_table': 'userrecipe',
            },
        ),
        migrations.AddField(
            model_name='recipechanges',
            name='rid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Recipes'),
        ),
        migrations.AddField(
            model_name='recipecontains',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Recipes'),
        ),
        migrations.AlterUniqueTogether(
            name='recipecontains',
            unique_together={('iid', 'rid')},
        ),
    ]
